### ISSUE TITLE
Did not authenticate

### ISSUE THREAD

**Issue by kmaustral** [Artel250/Obsidian-Talk-with-Bard#1]
This looks useful. Thank you. I tried your method of getting the Cookie value, but it did not authenticate. I will keep trying.

**Comment by Artel250** [comment]
Hello, thank you for pointing out the issue.

It is quite strange because it works on my end. Could you please specify the device/OS you are using? 
You can also access the developer console in Obsidian using `Ctrl + Shift + i` and check for any plugin errors. 
Please send them here if you find any.

Additionally, please note that the token should end with a ".", so that may have been the issue.

**Comment by kmaustral** [comment]
Here is the console error:

plugin:chat-with-bard:143 Error: Unable to get the snim0e token
    at _Bard.getSnim0e (plugin:chat-with-bard:132:13)
    at async _Bard.getBard (plugin:chat-with-bard:140:7)
getBard @ plugin:chat-with-bard:143

I'm on the latest Windows.

And my token did end in .

Let me know if there's any other information you might need.

Thank you,
Kevin

**Comment by Artel250** [comment]
Wow, you've sent me on a wild goose chase...

The issue seems to have arisen because Google didn't intend for this functionality to be used outside of Google. They recently updated something on the backend, causing this problem. 

One fix is to add two more tokens, **__Secure-1PSIDCC** and **__Secure-1PSIDTS**, which can be found in the same place as **__Secure-1PSID** token. This solution has worked in Germany.

A patch will be released today to allow you to add these tokens to the plugin. Let me know if it works!

**Comment by kmaustral** [comment]
Thanks. That works fine now.
